version: '3'
services:

  prometheus:
#    image: prom/prometheus
#    image: shomaigu/prometheus-aicta
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: prometheus
#    volumes:
#      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always



  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always



  grafana:
#    image: grafana/grafana
    image: shomaigu/grafana-aicta
#    build:
#      context: ./grafana
#      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
#    volumes:
#      - ./grafana/grafanavarlib:/var/lib/grafana
#      - ./grafana/datasources:/etc/grafana/provisioning/datasources
#      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards



  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command: "--config.file=/etc/alertmanager/config.yaml"
    ports:
      - 9093:9093
    restart: always
   


  blackbox_exporter:
    container_name: blackbox_exporter
    build:
      context: ./black
      dockerfile: Dockerfile
#    image: prom/blackbox-exporter:latest
#    image: shomaigu/black-aicta
#    volumes:
#      - ./black/config.yml:/etc/blackbox_exporter/config.yml
    command: "--config.file=/etc/blackbox_exporter/config.yml"
    ports:
      - 9115:9115
    restart: always



  snmp_exporter:
    container_name: snmp_exporter
#    build:
#      context: ./snmp-expoter
#      dockerfile: Dockerfile
    image: prom/snmp-exporter:latest
#    volumes:
#      - ./snmp-expoter/snmp.yml:/etc/snmp_exporter/snmp.yml
    ports:
      - 9116:9116
    restart: always




